export const SOCIAL_PLATFORMS = [
  { id: 'instagram', name: 'Instagram', category: 'social' as const, icon: 'Instagram' },
  { id: 'tiktok', name: 'TikTok', category: 'social' as const, icon: 'Video' },
  { id: 'facebook', name: 'Facebook', category: 'social' as const, icon: 'Facebook' },
  { id: 'twitter', name: 'Twitter/X', category: 'social' as const, icon: 'Twitter' },
  { id: 'linkedin', name: 'LinkedIn', category: 'professional' as const, icon: 'Linkedin' },
  { id: 'pinterest', name: 'Pinterest', category: 'social' as const, icon: 'Image' },
  { id: 'snapchat', name: 'Snapchat', category: 'social' as const, icon: 'Camera' },
  { id: 'reddit', name: 'Reddit', category: 'social' as const, icon: 'MessageSquare' },
  { id: 'threads', name: 'Threads', category: 'social' as const, icon: 'AtSign' },
  { id: 'bluesky', name: 'Bluesky', category: 'social' as const, icon: 'Cloud' },
  { id: 'mastodon', name: 'Mastodon', category: 'social' as const, icon: 'Users' },
  { id: 'tumblr', name: 'Tumblr', category: 'social' as const, icon: 'FileText' },
  { id: 'medium', name: 'Medium', category: 'professional' as const, icon: 'BookOpen' },
  { id: 'substack', name: 'Substack', category: 'professional' as const, icon: 'Mail' },
  { id: 'patreon', name: 'Patreon', category: 'social' as const, icon: 'Heart' },
  { id: 'vk', name: 'VKontakte', category: 'social' as const, icon: 'Globe' },
  { id: 'weibo', name: 'Weibo', category: 'social' as const, icon: 'Globe' },
  { id: 'wechat', name: 'WeChat', category: 'messaging' as const, icon: 'MessageCircle' },
  { id: 'line', name: 'LINE', category: 'messaging' as const, icon: 'MessageCircle' },
  { id: 'kakaotalk', name: 'KakaoTalk', category: 'messaging' as const, icon: 'MessageCircle' },
];

export const VIDEO_PLATFORMS = [
  { id: 'youtube', name: 'YouTube', category: 'video' as const, icon: 'Youtube' },
  { id: 'vimeo', name: 'Vimeo', category: 'video' as const, icon: 'Video' },
  { id: 'dailymotion', name: 'Dailymotion', category: 'video' as const, icon: 'Video' },
  { id: 'rumble', name: 'Rumble', category: 'video' as const, icon: 'Video' },
  { id: 'odysee', name: 'Odysee', category: 'video' as const, icon: 'Video' },
  { id: 'kick', name: 'Kick', category: 'video' as const, icon: 'Zap' },
  { id: 'peertube', name: 'PeerTube', category: 'video' as const, icon: 'Video' },
];

export const GAMING_PLATFORMS = [
  { id: 'twitch', name: 'Twitch', category: 'gaming' as const, icon: 'Twitch' },
  { id: 'discord', name: 'Discord', category: 'gaming' as const, icon: 'MessageSquare' },
  { id: 'steam', name: 'Steam', category: 'gaming' as const, icon: 'Gamepad2' },
  { id: 'epic', name: 'Epic Games', category: 'gaming' as const, icon: 'Gamepad2' },
  { id: 'xbox', name: 'Xbox Live', category: 'gaming' as const, icon: 'Gamepad2' },
  { id: 'playstation', name: 'PlayStation', category: 'gaming' as const, icon: 'Gamepad2' },
  { id: 'nintendo', name: 'Nintendo', category: 'gaming' as const, icon: 'Gamepad2' },
  { id: 'battlenet', name: 'Battle.net', category: 'gaming' as const, icon: 'Gamepad2' },
  { id: 'origin', name: 'Origin/EA', category: 'gaming' as const, icon: 'Gamepad2' },
  { id: 'gog', name: 'GOG Galaxy', category: 'gaming' as const, icon: 'Gamepad2' },
  { id: 'roblox', name: 'Roblox', category: 'gaming' as const, icon: 'Gamepad2' },
  { id: 'fortnite', name: 'Fortnite', category: 'gaming' as const, icon: 'Gamepad2' },
  { id: 'riot', name: 'Riot Games', category: 'gaming' as const, icon: 'Gamepad2' },
];

export const ECOMMERCE_PLATFORMS = [
  { id: 'shopify', name: 'Shopify', category: 'ecommerce' as const, icon: 'ShoppingBag' },
  { id: 'amazon', name: 'Amazon', category: 'ecommerce' as const, icon: 'ShoppingCart' },
  { id: 'etsy', name: 'Etsy', category: 'ecommerce' as const, icon: 'ShoppingBag' },
  { id: 'ebay', name: 'eBay', category: 'ecommerce' as const, icon: 'ShoppingCart' },
  { id: 'woocommerce', name: 'WooCommerce', category: 'ecommerce' as const, icon: 'ShoppingBag' },
  { id: 'bigcommerce', name: 'BigCommerce', category: 'ecommerce' as const, icon: 'ShoppingBag' },
  { id: 'squarespace', name: 'Squarespace Commerce', category: 'ecommerce' as const, icon: 'ShoppingBag' },
  { id: 'wix', name: 'Wix Stores', category: 'ecommerce' as const, icon: 'ShoppingBag' },
  { id: 'magento', name: 'Magento', category: 'ecommerce' as const, icon: 'ShoppingBag' },
  { id: 'prestashop', name: 'PrestaShop', category: 'ecommerce' as const, icon: 'ShoppingBag' },
  { id: 'alibaba', name: 'Alibaba', category: 'ecommerce' as const, icon: 'ShoppingCart' },
  { id: 'walmart', name: 'Walmart Marketplace', category: 'ecommerce' as const, icon: 'ShoppingCart' },
  { id: 'mercari', name: 'Mercari', category: 'ecommerce' as const, icon: 'ShoppingBag' },
  { id: 'poshmark', name: 'Poshmark', category: 'ecommerce' as const, icon: 'ShoppingBag' },
  { id: 'depop', name: 'Depop', category: 'ecommerce' as const, icon: 'ShoppingBag' },
  { id: 'redbubble', name: 'Redbubble', category: 'ecommerce' as const, icon: 'ShoppingBag' },
  { id: 'teespring', name: 'Spring (Teespring)', category: 'ecommerce' as const, icon: 'ShoppingBag' },
  { id: 'printful', name: 'Printful', category: 'ecommerce' as const, icon: 'Printer' },
  { id: 'printify', name: 'Printify', category: 'ecommerce' as const, icon: 'Printer' },
  { id: 'gumroad', name: 'Gumroad', category: 'ecommerce' as const, icon: 'ShoppingBag' },
  { id: 'teachable', name: 'Teachable', category: 'ecommerce' as const, icon: 'GraduationCap' },
  { id: 'thinkific', name: 'Thinkific', category: 'ecommerce' as const, icon: 'GraduationCap' },
  { id: 'kajabi', name: 'Kajabi', category: 'ecommerce' as const, icon: 'GraduationCap' },
  { id: 'udemy', name: 'Udemy', category: 'ecommerce' as const, icon: 'GraduationCap' },
  { id: 'skillshare', name: 'Skillshare', category: 'ecommerce' as const, icon: 'GraduationCap' },
  { id: 'coursera', name: 'Coursera', category: 'ecommerce' as const, icon: 'GraduationCap' },
];

export const MESSAGING_PLATFORMS = [
  { id: 'whatsapp', name: 'WhatsApp Business', category: 'messaging' as const, icon: 'MessageCircle' },
  { id: 'telegram', name: 'Telegram', category: 'messaging' as const, icon: 'Send' },
  { id: 'slack', name: 'Slack', category: 'messaging' as const, icon: 'Hash' },
  { id: 'teams', name: 'Microsoft Teams', category: 'messaging' as const, icon: 'Users' },
  { id: 'skype', name: 'Skype', category: 'messaging' as const, icon: 'Video' },
  { id: 'messenger', name: 'Facebook Messenger', category: 'messaging' as const, icon: 'MessageCircle' },
  { id: 'viber', name: 'Viber', category: 'messaging' as const, icon: 'Phone' },
  { id: 'signal', name: 'Signal', category: 'messaging' as const, icon: 'Lock' },
];

export const OTHER_PLATFORMS = [
  { id: 'spotify', name: 'Spotify for Creators', category: 'other' as const, icon: 'Music' },
  { id: 'soundcloud', name: 'SoundCloud', category: 'other' as const, icon: 'Music' },
  { id: 'audiomack', name: 'Audiomack', category: 'other' as const, icon: 'Music' },
  { id: 'bandcamp', name: 'Bandcamp', category: 'other' as const, icon: 'Music' },
  { id: 'applemusic', name: 'Apple Music', category: 'other' as const, icon: 'Music' },
  { id: 'deezer', name: 'Deezer', category: 'other' as const, icon: 'Music' },
  { id: 'tidal', name: 'Tidal', category: 'other' as const, icon: 'Music' },
  { id: 'mixcloud', name: 'Mixcloud', category: 'other' as const, icon: 'Music' },
  { id: 'clubhouse', name: 'Clubhouse', category: 'other' as const, icon: 'Radio' },
  { id: 'spotify-podcasts', name: 'Spotify Podcasts', category: 'other' as const, icon: 'Mic' },
  { id: 'apple-podcasts', name: 'Apple Podcasts', category: 'other' as const, icon: 'Mic' },
  { id: 'google-podcasts', name: 'Google Podcasts', category: 'other' as const, icon: 'Mic' },
  { id: 'anchor', name: 'Anchor', category: 'other' as const, icon: 'Mic' },
  { id: 'opensea', name: 'OpenSea', category: 'other' as const, icon: 'Hexagon' },
  { id: 'rarible', name: 'Rarible', category: 'other' as const, icon: 'Hexagon' },
  { id: 'foundation', name: 'Foundation', category: 'other' as const, icon: 'Hexagon' },
  { id: 'behance', name: 'Behance', category: 'professional' as const, icon: 'Palette' },
  { id: 'dribbble', name: 'Dribbble', category: 'professional' as const, icon: 'Palette' },
  { id: 'deviantart', name: 'DeviantArt', category: 'other' as const, icon: 'Palette' },
  { id: 'artstation', name: 'ArtStation', category: 'professional' as const, icon: 'Palette' },
  { id: 'github', name: 'GitHub', category: 'professional' as const, icon: 'Github' },
  { id: 'gitlab', name: 'GitLab', category: 'professional' as const, icon: 'Code' },
  { id: 'stackoverflow', name: 'Stack Overflow', category: 'professional' as const, icon: 'Code' },
  { id: 'producthunt', name: 'Product Hunt', category: 'professional' as const, icon: 'Rocket' },
  { id: 'indiegogo', name: 'Indiegogo', category: 'other' as const, icon: 'DollarSign' },
  { id: 'kickstarter', name: 'Kickstarter', category: 'other' as const, icon: 'DollarSign' },
  { id: 'onlyfans', name: 'OnlyFans', category: 'other' as const, icon: 'Users' },
  { id: 'fanhouse', name: 'Fanhouse', category: 'other' as const, icon: 'Users' },
  { id: 'cameo', name: 'Cameo', category: 'other' as const, icon: 'Video' },
  { id: 'fiverr', name: 'Fiverr', category: 'professional' as const, icon: 'Briefcase' },
  { id: 'upwork', name: 'Upwork', category: 'professional' as const, icon: 'Briefcase' },
  { id: 'freelancer', name: 'Freelancer', category: 'professional' as const, icon: 'Briefcase' },
];

export const ALL_PLATFORMS = [
  ...SOCIAL_PLATFORMS,
  ...VIDEO_PLATFORMS,
  ...GAMING_PLATFORMS,
  ...ECOMMERCE_PLATFORMS,
  ...MESSAGING_PLATFORMS,
  ...OTHER_PLATFORMS,
];
