export interface Integration {
  id: string;
  name: string;
  category: string;
  description: string;
  enabled: boolean;
  configured: boolean;
  tier: 'critical' | 'high' | 'medium' | 'low';
  credentials: {
    [key: string]: string;
  };
  capabilities: string[];
  autonomousActions: string[];
}

export const INTEGRATION_CATEGORIES = {
  REVENUE: 'Revenue Generation',
  PAYMENT: 'Payment Processing',
  ADVERTISING: 'Advertising & Traffic',
  SOCIAL: 'Social Media',
  CONTENT: 'Content Creation',
  EMAIL: 'Email & SMS Marketing',
  FULFILLMENT: 'Fulfillment & Logistics',
  MANUFACTURING: '3D Printing & Manufacturing',
  ANALYTICS: 'Analytics & Data',
  TRENDS: 'Trend Detection',
  SUPPORT: 'Customer Support',
  AFFILIATE: 'Affiliate & Influencer',
  FINANCE: 'Finance & Accounting',
  PROJECT: 'Project Management',
  LEGAL: 'Legal & Compliance',
  CRYPTO: 'Crypto & Web3',
  IOT: 'IoT & Smart Home',
  GAMING: 'Gaming & Entertainment',
  AI: 'AI/ML Infrastructure',
  HOSTING: 'Domain & Hosting',
};

export const INTEGRATIONS: Integration[] = [
  {
    id: 'shopify',
    name: 'Shopify',
    category: INTEGRATION_CATEGORIES.REVENUE,
    description: 'Full store management, product listings, inventory, orders',
    enabled: false,
    configured: false,
    tier: 'critical',
    credentials: {
      apiKey: '',
      apiSecret: '',
      shopDomain: '',
    },
    capabilities: ['Create Products', 'Manage Inventory', 'Process Orders', 'Auto-pricing'],
    autonomousActions: ['List trending products', 'Adjust prices based on demand', 'Process orders automatically'],
  },
  {
    id: 'stripe',
    name: 'Stripe',
    category: INTEGRATION_CATEGORIES.PAYMENT,
    description: 'Payment processing, subscriptions, invoicing',
    enabled: false,
    configured: false,
    tier: 'critical',
    credentials: {
      publishableKey: '',
      secretKey: '',
    },
    capabilities: ['Process Payments', 'Manage Subscriptions', 'Create Invoices', 'Refunds'],
    autonomousActions: ['Process payments', 'Handle refunds under $50', 'Manage subscription lifecycles'],
  },
  {
    id: 'meta_ads',
    name: 'Meta Ads (Facebook/Instagram)',
    category: INTEGRATION_CATEGORIES.ADVERTISING,
    description: 'Full campaign management for Facebook and Instagram ads',
    enabled: false,
    configured: false,
    tier: 'critical',
    credentials: {
      accessToken: '',
      adAccountId: '',
    },
    capabilities: ['Create Campaigns', 'A/B Testing', 'Budget Management', 'Audience Targeting'],
    autonomousActions: ['Create ad campaigns', 'Kill underperforming ads', 'Scale winners', 'Optimize budgets'],
  },
  {
    id: 'google_ads',
    name: 'Google Ads',
    category: INTEGRATION_CATEGORIES.ADVERTISING,
    description: 'Search, Display, YouTube, Shopping ads',
    enabled: false,
    configured: false,
    tier: 'critical',
    credentials: {
      clientId: '',
      clientSecret: '',
      developerToken: '',
      refreshToken: '',
    },
    capabilities: ['Search Ads', 'Display Ads', 'YouTube Ads', 'Shopping Ads', 'Keyword Optimization'],
    autonomousActions: ['Manage ad campaigns', 'Optimize keywords', 'Adjust bids', 'Test creatives'],
  },
  {
    id: 'instagram',
    name: 'Instagram',
    category: INTEGRATION_CATEGORIES.SOCIAL,
    description: 'Post content, stories, reels, IGTV',
    enabled: false,
    configured: false,
    tier: 'critical',
    credentials: {
      accessToken: '',
      userId: '',
    },
    capabilities: ['Post Photos', 'Post Videos', 'Stories', 'Reels', 'IGTV'],
    autonomousActions: ['Schedule posts', 'Respond to comments', 'Post stories', 'Analyze engagement'],
  },
  {
    id: 'tiktok',
    name: 'TikTok',
    category: INTEGRATION_CATEGORIES.SOCIAL,
    description: 'Upload videos, analytics',
    enabled: false,
    configured: false,
    tier: 'critical',
    credentials: {
      accessToken: '',
    },
    capabilities: ['Upload Videos', 'Analytics', 'Trend Detection'],
    autonomousActions: ['Upload content', 'Optimize posting times', 'Track trending sounds'],
  },
  {
    id: 'youtube',
    name: 'YouTube',
    category: INTEGRATION_CATEGORIES.SOCIAL,
    description: 'Upload videos, live streaming, community posts',
    enabled: false,
    configured: false,
    tier: 'high',
    credentials: {
      clientId: '',
      clientSecret: '',
      refreshToken: '',
    },
    capabilities: ['Upload Videos', 'Live Stream', 'Community Posts', 'Analytics'],
    autonomousActions: ['Upload videos', 'Optimize titles/descriptions', 'Schedule content'],
  },
  {
    id: 'openai',
    name: 'OpenAI (GPT-4)',
    category: INTEGRATION_CATEGORIES.AI,
    description: 'Content generation, analysis, decision making',
    enabled: false,
    configured: false,
    tier: 'critical',
    credentials: {
      apiKey: '',
    },
    capabilities: ['Text Generation', 'Image Generation (DALL-E)', 'Analysis', 'Transcription'],
    autonomousActions: ['Generate content', 'Write copy', 'Analyze data', 'Make decisions'],
  },
  {
    id: 'mailchimp',
    name: 'Mailchimp',
    category: INTEGRATION_CATEGORIES.EMAIL,
    description: 'Email marketing, automation, segmentation',
    enabled: false,
    configured: false,
    tier: 'high',
    credentials: {
      apiKey: '',
      serverPrefix: '',
    },
    capabilities: ['Email Campaigns', 'Automation', 'Segmentation', 'A/B Testing'],
    autonomousActions: ['Send campaigns', 'Segment lists', 'Test subject lines', 'Nurture leads'],
  },
  {
    id: 'printful',
    name: 'Printful',
    category: INTEGRATION_CATEGORIES.FULFILLMENT,
    description: 'Print-on-demand for apparel, mugs, posters',
    enabled: false,
    configured: false,
    tier: 'high',
    credentials: {
      apiKey: '',
    },
    capabilities: ['Product Fulfillment', 'Design Upload', 'Order Management'],
    autonomousActions: ['Create products', 'Fulfill orders', 'Track shipments'],
  },
  {
    id: 'amazon_seller',
    name: 'Amazon Seller Central',
    category: INTEGRATION_CATEGORIES.REVENUE,
    description: 'FBA automation, product listings',
    enabled: false,
    configured: false,
    tier: 'high',
    credentials: {
      sellerId: '',
      mwsAuthToken: '',
      marketplaceId: '',
    },
    capabilities: ['List Products', 'FBA Management', 'Order Processing', 'Inventory'],
    autonomousActions: ['List products', 'Manage FBA inventory', 'Optimize pricing'],
  },
  {
    id: 'etsy',
    name: 'Etsy',
    category: INTEGRATION_CATEGORIES.REVENUE,
    description: 'Handmade and digital products',
    enabled: false,
    configured: false,
    tier: 'medium',
    credentials: {
      apiKey: '',
      sharedSecret: '',
      oauthToken: '',
    },
    capabilities: ['List Products', 'Order Management', 'Shop Analytics'],
    autonomousActions: ['Create listings', 'Optimize tags', 'Process orders'],
  },
  {
    id: 'twitter',
    name: 'Twitter/X',
    category: INTEGRATION_CATEGORIES.SOCIAL,
    description: 'Post tweets, threads, track trends',
    enabled: false,
    configured: false,
    tier: 'high',
    credentials: {
      apiKey: '',
      apiSecret: '',
      accessToken: '',
      accessTokenSecret: '',
    },
    capabilities: ['Post Tweets', 'Threads', 'Trend Tracking', 'Engagement'],
    autonomousActions: ['Post content', 'Respond to mentions', 'Track trends'],
  },
  {
    id: 'linkedin',
    name: 'LinkedIn',
    category: INTEGRATION_CATEGORIES.SOCIAL,
    description: 'Professional networking and content',
    enabled: false,
    configured: false,
    tier: 'medium',
    credentials: {
      clientId: '',
      clientSecret: '',
      accessToken: '',
    },
    capabilities: ['Post Articles', 'Share Content', 'Network Building'],
    autonomousActions: ['Post content', 'Engage with connections', 'Share insights'],
  },
  {
    id: 'tiktok_ads',
    name: 'TikTok Ads',
    category: INTEGRATION_CATEGORIES.ADVERTISING,
    description: 'TikTok advertising platform',
    enabled: false,
    configured: false,
    tier: 'high',
    credentials: {
      accessToken: '',
      advertiserId: '',
    },
    capabilities: ['Video Ads', 'Spark Ads', 'Audience Targeting', 'Campaign Management'],
    autonomousActions: ['Create campaigns', 'Optimize audiences', 'Test creatives'],
  },
  {
    id: 'google_analytics',
    name: 'Google Analytics',
    category: INTEGRATION_CATEGORIES.ANALYTICS,
    description: 'Website and app analytics',
    enabled: false,
    configured: false,
    tier: 'high',
    credentials: {
      measurementId: '',
      apiSecret: '',
    },
    capabilities: ['Traffic Analysis', 'User Behavior', 'Conversion Tracking'],
    autonomousActions: ['Track performance', 'Identify trends', 'Optimize conversions'],
  },
  {
    id: 'elevenlabs',
    name: 'ElevenLabs',
    category: INTEGRATION_CATEGORIES.CONTENT,
    description: 'Voice cloning and text-to-speech',
    enabled: false,
    configured: false,
    tier: 'medium',
    credentials: {
      apiKey: '',
    },
    capabilities: ['Voice Cloning', 'Text-to-Speech', 'Voice Library'],
    autonomousActions: ['Generate voiceovers', 'Clone voices', 'Create audio content'],
  },
  {
    id: 'twilio',
    name: 'Twilio',
    category: INTEGRATION_CATEGORIES.EMAIL,
    description: 'SMS, voice, WhatsApp messaging',
    enabled: false,
    configured: false,
    tier: 'medium',
    credentials: {
      accountSid: '',
      authToken: '',
      phoneNumber: '',
    },
    capabilities: ['SMS Marketing', 'Voice Calls', 'WhatsApp'],
    autonomousActions: ['Send SMS campaigns', 'Handle customer calls', 'WhatsApp automation'],
  },
  {
    id: 'quickbooks',
    name: 'QuickBooks',
    category: INTEGRATION_CATEGORIES.FINANCE,
    description: 'Accounting and bookkeeping',
    enabled: false,
    configured: false,
    tier: 'high',
    credentials: {
      clientId: '',
      clientSecret: '',
      realmId: '',
    },
    capabilities: ['Expense Tracking', 'Invoicing', 'Tax Reports', 'P&L Statements'],
    autonomousActions: ['Categorize expenses', 'Generate reports', 'Track revenue'],
  },
  {
    id: 'slack',
    name: 'Slack',
    category: INTEGRATION_CATEGORIES.PROJECT,
    description: 'Team communication and notifications',
    enabled: false,
    configured: false,
    tier: 'medium',
    credentials: {
      botToken: '',
      webhookUrl: '',
    },
    capabilities: ['Notifications', 'Team Chat', 'File Sharing'],
    autonomousActions: ['Send updates', 'Alert team', 'Share reports'],
  },
  {
    id: 'hubspot',
    name: 'HubSpot',
    category: INTEGRATION_CATEGORIES.SUPPORT,
    description: 'CRM and marketing automation',
    enabled: false,
    configured: false,
    tier: 'high',
    credentials: {
      apiKey: '',
    },
    capabilities: ['Contact Management', 'Email Automation', 'Sales Pipeline', 'Analytics'],
    autonomousActions: ['Manage contacts', 'Score leads', 'Automate follow-ups'],
  },
  {
    id: 'pinterest',
    name: 'Pinterest',
    category: INTEGRATION_CATEGORIES.SOCIAL,
    description: 'Pin creation and boards',
    enabled: false,
    configured: false,
    tier: 'medium',
    credentials: {
      accessToken: '',
    },
    capabilities: ['Create Pins', 'Manage Boards', 'Analytics'],
    autonomousActions: ['Post pins', 'Optimize descriptions', 'Track trends'],
  },
  {
    id: 'canva',
    name: 'Canva',
    category: INTEGRATION_CATEGORIES.CONTENT,
    description: 'Graphic design automation',
    enabled: false,
    configured: false,
    tier: 'medium',
    credentials: {
      apiKey: '',
    },
    capabilities: ['Design Creation', 'Brand Kit', 'Template Access'],
    autonomousActions: ['Generate designs', 'Create social graphics', 'Brand consistency'],
  },
  {
    id: 'octoprint',
    name: 'OctoPrint',
    category: INTEGRATION_CATEGORIES.MANUFACTURING,
    description: '3D printer control and monitoring',
    enabled: false,
    configured: false,
    tier: 'low',
    credentials: {
      apiKey: '',
      serverUrl: '',
    },
    capabilities: ['Printer Control', 'Job Queue', 'Monitoring', 'File Management'],
    autonomousActions: ['Queue print jobs', 'Monitor progress', 'Manage files'],
  },
  {
    id: 'coinbase',
    name: 'Coinbase',
    category: INTEGRATION_CATEGORIES.CRYPTO,
    description: 'Cryptocurrency trading and payments',
    enabled: false,
    configured: false,
    tier: 'low',
    credentials: {
      apiKey: '',
      apiSecret: '',
    },
    capabilities: ['Trading', 'Payments', 'Price Alerts', 'Portfolio Management'],
    autonomousActions: ['Accept crypto payments', 'Track portfolio', 'Price alerts'],
  },
  {
    id: 'google_trends',
    name: 'Google Trends',
    category: INTEGRATION_CATEGORIES.TRENDS,
    description: 'Trend detection and forecasting',
    enabled: false,
    configured: false,
    tier: 'high',
    credentials: {},
    capabilities: ['Trend Detection', 'Search Volume', 'Regional Interest'],
    autonomousActions: ['Detect trends', 'Predict viral topics', 'Find opportunities'],
  },
  {
    id: 'semrush',
    name: 'SEMrush',
    category: INTEGRATION_CATEGORIES.ANALYTICS,
    description: 'SEO and competitive analysis',
    enabled: false,
    configured: false,
    tier: 'medium',
    credentials: {
      apiKey: '',
    },
    capabilities: ['Keyword Research', 'Competitor Analysis', 'Backlink Tracking'],
    autonomousActions: ['Research keywords', 'Analyze competitors', 'Track rankings'],
  },
  {
    id: 'zapier',
    name: 'Zapier',
    category: INTEGRATION_CATEGORIES.PROJECT,
    description: 'Workflow automation',
    enabled: false,
    configured: false,
    tier: 'medium',
    credentials: {
      apiKey: '',
    },
    capabilities: ['Workflow Automation', 'App Integration', 'Task Automation'],
    autonomousActions: ['Create workflows', 'Automate tasks', 'Connect apps'],
  },
  {
    id: 'airtable',
    name: 'Airtable',
    category: INTEGRATION_CATEGORIES.PROJECT,
    description: 'Database and project management',
    enabled: false,
    configured: false,
    tier: 'medium',
    credentials: {
      apiKey: '',
      baseId: '',
    },
    capabilities: ['Database Management', 'Project Tracking', 'Collaboration'],
    autonomousActions: ['Manage data', 'Track projects', 'Generate reports'],
  },
];
